name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet:     #Job Name
    runs-on: ubuntu-latest
    
    env:            # Environment variable at the job level
      MY_ENV: "John Doe"
      
    steps:     
      - name: Greet the User    # First Step
        run: echo "Hello World!"

      - run: ls -l                   # Remove Later
      - uses: actions/checkout@v4    # Remove Later
      - run: ls -l                   # Remove Later
          
      - name: Run a multi-line script # Second Step
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"

